### ISSUE TITLE
One stepper disengages

### ISSUE THREAD

**Issue by devburke** [MarginallyClever/Makelangelo-firmware#8] opened 2016-06-17 17:28 UTC
For troubleshooting reasons, I had to reflash the firmware on the Makelangelo I had working correctly. However, now I notice that whenever I tell the Makelangelo software to move the gondola around, once it does, it keeps the left motor engaged to hold its position, but the left stepper disengages and it drifts.

**Comment by i-make-robots** [comment] 2016-06-17 17:33
Do you have the previous firmware?  I have been unable to reproduce the problem on the machines we're building here.

**Comment by i-make-robots** [comment] 2016-06-17 17:33
I wonder if you have previous firmware so we can diff and find what's changed.

**Comment by devburke** [comment] 2016-06-17 17:36
I just tried it using the latest release. I should've known better than to mess with what's working :)

**Comment by i-make-robots** [comment] 2016-06-17 17:53
@devburke so this issue is fixed for you?  Some people have reported similar and I'd like to know what you did to fix it, please.

**Comment by devburke** [comment] 2016-06-17 18:00
Oh no, sorry, should've been more clear. It's still doing it with the latest release. Right now, I'm not focusing on that, I'm prioritizing figuring out why one of my machines moves really slow. Swapping out parts between the working and broken ones, etc. So far I think it's looking like the shield is the problem. My theory is corrosion from the flux in my solder is messing things up, but we'll see. It could also be a problem with support for that version of the AFMS.

That doesn't say anything with regard to this issue though.

**Comment by i-make-robots** [comment] 2016-06-28 19:42
Possible fix just checked in 1d8b0fadfa7e39ad0435949500c24e5395a1d05c.  Please flash your firmware and try it.  Reason for bug:  My brain fell out of my head.

**Comment by i-make-robots** [comment] 2016-06-28 20:31
Confirmed fixed.

**Closed by i-make-robots** 2016-06-28 20:31 UTC
